### ISSUE TITLE
PostgreSQL driver: feed DEFAULT to columns instead of NULL.

### ISSUE THREAD

**Issue by kolypto** [dresende/node-orm2#391]
Using the following model

```
var Upload = db.define('Upload', {
        id: Number,
        name: String
    }, {
        id: 'id',
        table: 'uploads'
    });
```

Against the following schema:

```
CREATE SEQUENCE "uploads_id_seq";
CREATE TABLE "uploads" (
    "id" int NOT NULL DEFAULT nextval('uploads_id_seq'),
    "name" varchar(255) NOT NULL
);
ALTER SEQUENCE "uploads_id_seq" OWNED BY uploads.id;
CREATE UNIQUE INDEX "idx:uploads:id" ON "uploads" ("id");
```

I try the following:

```
Upload.create({}, function(){...});
Upload.create({ id: undefined }, function(){...});
```

All give the following error:

> error: null value in column "id" violates not-null constraint

This happens because PostgreSQL, when said to insert `NULL`, inserts as requested. To insert the default value, one should put `DEFAULT` there, or omit the column when inserting.

---

In general, a `NOT NULL` column will never allow `NULL`, and for `NULL` columns -- this value is the default _default value_, so to say.

I'm suggesting to always use `DEFAULT` when inserting `null`s into PostgreSQL, or at least handle `undefined` this way.

**Comment by cjnqt** [comment]
@dxg This is still an issue as far as I can see.

The problem is this: when we call `Model.create(...)`, every parameter that is not specified in the `create` should receive its default value. The generated query sets those values to NULL, and Postgres stores a NULL value, not any DEFAULT value specified in the database.

An example: 

Let's say we have a Postgres table with two columns: 
```
CREATE TABLE "user" ("first_name" TEXT, "random_string" TEXT DEFAULT gen_random_bytes(16))
```
the default value for the column `random_string` is random data, generated by a postgres function.

The query `INSERT INTO "user" ("first_name") VALUES ("PeterPan")` will generate a row with both  first_name and random_string populated.

But using `User.create({ 'first_name': 'PeterPan' }, function(err, result)` creates the SQL-query
`INSERT INTO "user" ("first_name", "random_string") VALUES ("PeterPan", **NULL**)` and this will generate a row with only first_name populated.
