### ISSUE TITLE
node-orm2 or sequelize?

### ISSUE THREAD

**Issue by jamesone** [dresende/node-orm2#747]
Hey all, 

Have any of you had experience using both sequelize and node-orm2? If so, which one is best? I've used sequelize quite a bit and just came across this & it looks good, really good!

**Comment by ohjames** [comment]
@jamesone http://blog.chilon.net/node/javascript/2017/03/03/on-node-orm2.html

**Comment by ssbrewster** [comment]
You can promisify with bluebird e.g.
```
const models = Promise.promisify(require('../models'));

models('yourDb', false)
    .then(db => doSomethingWithDb)
```

You might also need to [set the context](http://bluebirdjs.com/docs/api/promise.promisify.html) right...but yes this is a pain and you also should really read [this](https://medium.com/the-node-js-collection/why-the-hell-would-you-use-node-js-4b053b94ab8e#.h4hpymq2x) and then decide to use python and django instead 😄 . If you stick with node sequelize looks good, loopback a more full featured option.

**Comment by ohjames** [comment]
You can't promisify with bluebird though, well only partially, due to https://github.com/dresende/node-orm2/issues/773 and see also https://github.com/rafaelkaufmann/q-orm/issues/1.

For many reasons orm2 is a terrible choice, thankfully I'm not working with the client who made me use it anymore ;) sequelize is better, I will check out loopback, but honestly I'm starting to feel that ORMs often aren't a good idea and there's plenty of recent articles by people who feel the same.

**Comment by ohjames** [comment]
Python/Django is pretty cool, used it a lot. Slightly prefer rails to Django though, much terser code due to ruby's advanced metaprogramming. Node is still cool though, despite the lack of mature ORMs, with recent projects I've been using rethinkdb without an ORM and finding there's less boilerplate when I'm just writing my joins directly.

**Comment by ssbrewster** [comment]
`const doSomethingAsync = Promise.promisify(db.models.my_model.create, {context: db.models})` is working fine for me in addition to the example i gave above. Thanks for reference to q-orm issue. Currently i do have to use orm2 haha but i'm going to raise exploring other options while the API i'm working on is still fairly small.

Loopback is good but like anything there are drawbacks, context handling was an issue for me but i think they are improving that in 3.0.

I want to take a look at rethinkdb and not using ORMs is an interesting approach, I guess it depends on the ORMs available.

**Comment by dxg** [comment]
Promise support is baked into `node-orm2` now however I recommend using an actively maintained ORM like Bookshselfjs or Sequelize.
